name: Core tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang make

    - name: compilation
      run: make re

    - name: core tests
      run: |
        make
        cd ./tests/
        make
        chmod +x hopt_tests tester.sh
        bash tester.sh
